---
- name: Configure system with Nix packages
  hosts: localhost
  become: true
  tasks:
    - name: Set correct locale
      shell: |
        echo "🌐 Konfiguriere Locale-Einstellungen..."
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        locale-gen C.UTF-8
      args:
        executable: /bin/bash

    - name: Load Nix profile environment
      shell: |
        . /home/alex/.nix-profile/etc/profile.d/nix.sh
      args:
        executable: /bin/bash

    - name: Install tools via Nix
      become_user: alex
      shell: |
        . /home/alex/.nix-profile/etc/profile.d/nix.sh
        nix-env -iA \
          nixpkgs.zsh \
          nixpkgs.tmux \
          nixpkgs.stow \
          nixpkgs.ripgrep \
          nixpkgs.fzf \
          nixpkgs.fd \
          nixpkgs.git \
          nixpkgs.neovim \
          nixpkgs.lua \
          nixpkgs.gcc \
          nixpkgs.gnumake
      args:
        executable: /bin/bash

    - name: Stow dotfiles
      become_user: alex
      shell: |
        cd /home/alex/.local/share/dotfiles
        stow --restow */
      args:
        executable: /bin/bash

    - name: Set Zsh as default shell (again to ensure consistency)
      user:
        name: alex
        shell: /home/alex/.nix-profile/bin/zsh
